name: Build & Deploy Branch

on:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: deploy-publish
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Node.js dependencies
        run: npm ci

      - name: Build frontend (Vite)
        run: npm run build

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none

      - name: Install Composer dependencies (with vendor)
        run: composer install --no-dev --prefer-dist --no-interaction --no-progress --optimize-autoloader

      - name: Prepare dist folder
        run: |
          mkdir dist
          rsync -a ./ dist/ \
            --exclude ".git" \
            --exclude ".github" \
            --exclude "tests" \
            --exclude ".env*" \
            --exclude "storage/logs" \
            --exclude "storage/framework/sessions" \
            --exclude "storage/framework/views"

          # Ensure build output exists
          mkdir -p dist/public/build
          rsync -a public/build/ dist/public/build/ || true
          test -f dist/public/build/manifest.json

          echo ".env" > dist/.gitignore
          echo "storage/*" >> dist/.gitignore

      - name: Push to deploy branch
        env:
          REPO_URL: https://x-access-token:${{ secrets.DEPLOY_TOKEN }}@github.com/${{ github.repository }}.git
        run: |
          set -e

          # Clone fresh deploy branch
          git clone --depth=1 "$REPO_URL" deploy-repo || true
          cd deploy-repo

          if git rev-parse --verify deploy >/dev/null 2>&1; then
            git checkout deploy
          else
            git checkout --orphan deploy
          fi

          cd ..
          rsync -a --delete dist/ deploy-repo/

          cd deploy-repo
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -A

          git commit -m "Auto deploy from ${GITHUB_SHA}" || echo "No changes to commit"
          git push -f "$REPO_URL" HEAD:deploy
