name: Build & Publish Deploy Branch

on:
  push:
    branches: [ main ]

permissions:
  contents: write

concurrency:
  group: deploy-publish
  cancel-in-progress: true

env:
  APP_PATH: .

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Node deps
        working-directory: ${{ env.APP_PATH }}
        run: npm ci

      - name: Build assets (Vite)
        working-directory: ${{ env.APP_PATH }}
        run: npm run build

      - name: Show Vite output (debug)
        working-directory: ${{ env.APP_PATH }}
        run: |
          ls -la public || true
          ls -la public/build || true
          test -f public/build/manifest.json

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none

      - name: Install Composer deps (prod)
        working-directory: ${{ env.APP_PATH }}
        run: composer install --no-dev --prefer-dist --no-interaction --no-progress --optimize-autoloader

      - name: Prepare dist snapshot
        run: |
          set -e
          mkdir -p dist
          rsync -a "${APP_PATH}/" dist/ \
            --exclude ".git" --exclude ".github" --exclude "node_modules" \
            --exclude "tests" --exclude ".env*"

          mkdir -p dist/public/build
          rsync -a "${APP_PATH}/public/build/" dist/public/build/ || true
          test -f dist/public/build/manifest.json

          printf "%s\n" \
            ".env" \
            ".env.*" \
            "storage/logs" \
            "storage/framework/cache/data/*" \
            "storage/framework/sessions/*" \
            "storage/framework/views/*" > dist/.gitignore

      - name: Publish deploy branch (fast-forward, no force)
        env:
          REPO_URL: https://x-access-token:${{ secrets.DeployToken }}@github.com/${{ github.repository }}.git
          GIT_TRACE: "1"
          GIT_CURL_VERBOSE: "1"
        run: |
          set -euo pipefail
          set -x
          echo "Preflight auth check against $REPO_URL"
          git ls-remote "$REPO_URL" >/dev/null

          if git ls-remote --exit-code "$REPO_URL" refs/heads/deploy >/dev/null 2>&1; then
            git clone --depth=1 --branch=deploy "$REPO_URL" deploy-repo
          else
            git clone --depth=1 "$REPO_URL" deploy-repo
            cd deploy-repo
            git checkout --orphan deploy
            git rm -rf .
            git config user.name "github-actions"
            git config user.email "actions@github.com"
            git commit --allow-empty -m "Initialize deploy branch"
            git push -v "$REPO_URL" HEAD:refs/heads/deploy
            cd ..
          fi

          cd deploy-repo
          git fetch origin deploy
          git checkout deploy
          git reset --hard origin/deploy

          cd ..
          rsync -a --delete dist/ deploy-repo/

          cd deploy-repo
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -A

          if git diff --cached --quiet; then
            echo "No changes to deploy."
            exit 0
          fi

          git commit -m "Deploy from ${GITHUB_SHA}"
          git fetch origin deploy
          # Force fast-forward or overwrite with new dist snapshot
          git reset --hard origin/deploy || true
          git pull origin deploy --rebase=false || true
          git push -f "$REPO_URL" HEAD:refs/heads/deploy

      - name: Deploy to cPanel via SSH
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: pitp.online
          username: ${{ secrets.FTP_USERNAME }}
          key: ${{ secrets.CPANEL_SSH_KEY }}
          script: |
            cd public_html/pitp.online/prod
            git fetch origin deploy
            git reset --hard origin/deploy
            echo "✅ Code pulled successfully from deploy branch!"
